// svelte-demo/src/App.svelte
<script>
  let count = 0
  $: doubled = count * 2
  function handleClick() {
    count++
  }
  $: {
    console.log(`the count is ${count}`)
  }
  $: if (count >= 10) {
    alert(`count is dangerously high!`)
    count = 9
  }
</script>

<main>
  <h1>{count}</h1>
  <h2>{doubled}</h2>
  <button on:click={handleClick}>+</button>
</main>

<style>
</style>

// react-beta/src/App.tsx
import { useState } from 'react'

let count = 0

function App() {
  console.log('render')

  const [count, setCount] = useState(0)
  function handleClick() {
    setCount(count + 1)
    console.log(count)
  }

  return (
    <div className="App">
      {count}
      <button onClick={handleClick}>add</button>
    </div>
  )
}

export default App
